platform: linux

image_resource:
  type: docker-image
  source:
    repository: python
    tag: 3-slim

inputs:
  - name: testapp

outputs:
  - name: image-params

run:
  path: ./testapp/.ci/build.sh
