resource_types:
- name: marathon
  type: docker-image
  source:
    repository: ckaznocha/marathon-resource

resources:
- name: testapp
  type: git
  source:
    uri: https://github.com/jerith/testapp
    branch: master
  webhook_token: prod-my-resource
  check_every: 30m

- name: testapp-image
  type: docker-image
  source:
    repository: jerithorg/testapp
    username: jerithbot
    password: {{jerithbot-dockerhub-key}}
  check_every: 30m

- name: testapp-marathon
  type: marathon
  source:
    app_id: jerith-testapp
    uri: http://10.215.33.193:8090/
  check_every: 30m

jobs:
- name: build-image
  plan:
  - get: testapp
    trigger: true
  - task: build
    file: testapp/.ci/build.yml
  - put: testapp-image
    params:
      build: testapp
      tag: image-params/tag
  - task: deploy
    file: testapp/.ci/deploy.yml
  - put: testapp-marathon
    params:
      app_json: deploy-params/testapp.json
      time_out: 60
      restart_if_no_update: true
