resource_types:
- name: marathon
  type: docker-image
  source:
    repository: ckaznocha/marathon-resource

resources:
- name: testapp
  type: git
  source:
    uri: https://github.com/jerith/testapp
    branch: master

- name: testapp-image
  type: docker-image
  source:
    repository: jerithorg/testapp
    username: jerithbot
    password: {{jerithbot-dockerhub-key}}

- name: testapp-marathon
  type: marathon
  source:
    app_id: testapp
    uri: http://localhost:8090/

jobs:
- name: build-image
  plan:
  - get: testapp
  - task: build
    file: testapp/.ci/build.yml
  - put: testapp-image
    params:
      build: testapp
      tag: image-params/tag
  - task: deploy
    file: testapp/.ci/deploy.yml
  - put: testapp-marathon
    params:
      app_json: deploy-params/testapp.json
      time_out: 30
